### ISSUE TITLE
marshal_with decorator?

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/flask-marshmallow#1]
I'm considering adding a `marshal_with` decorator, an idea from Flask-Restful: http://flask-restful.readthedocs.org/en/latest/fields.html . I can see how it might fit some use cases (e.g. integrating with Flask-Restful or Flask-API, which expect views to return dictionaries). However, I'm not fully convinced that it adds that much convenience to be worth the added code in this package.

**Comment by sloria** [comment]
I've decided against this. Making a proper HTTP response from a serializer's output is outside of flask-marshmallow's scope.

**Comment by Kamforka** [comment]
Hey sloria, 
Why did you decide against it?

I definitely think it would be a real benefit and would reduce a lot of boilerplate.

I can also help with the implementation if you don't have the time for this.

**Comment by sloria** [comment]
I decided against in in order to keep this library small and maintainable. From what I've seen, consuming libraries and apps end up creating their own bespoke `marshal_with`-like functionality that is specific to their use case (e.g. flask-apispec, flask-resty, flask-rest-api all do this).

**Comment by Kamforka** [comment]
I see your point, but for instance flask-apispec also overrides `use_kwargs` to meet its needs, so I guess it's not a big deal to override a simple `marshal_with` implementation either.

Also I believe that the functionality provided by `marshal_with` is not strictly related to `marshmallow` but it's kinda reasonable to have in `flask-marshmallow` as most of the time you end up returning the serialized result in a HTTP response.
