### ISSUE TITLE
URLFor serialization when attribute is `None` results in AttributeError

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/flask-marshmallow#10]
Found by @raj-kesavan in https://github.com/sloria/marshmallow/issues/114 : Serializing `None` with a `URLFor` or `Hyperlinks` field results in an `AttributeError`.

``` python
from flask import Flask
from flask_marshmallow import Marshmallow

app = Flask('testapp')

@app.route('/foo/<id>')
def foo(id):
    return '..'

ma = Marshmallow(app)

class FooSchema(ma.Schema):
    links = ma.URLFor('foo', id='<id>')

ctx = app.test_request_context()
ctx.push()

schema = FooSchema()
foo1 = {'id': 1}
print(schema.dump(foo1).data)  # {'links': '/foo/1'}

# This should raise a werkzueg BuildError, NOT an AttributeError
foo2 = {'id': None}
print(schema.dump(foo2).data)  # AttributeError: 'id' is not a valid attribute of {'id': None}

foo3 = {'id': 0}
print(schema.dump(foo3).data)  # AttributeError: 'id' is not a valid attribute of {'id': 0}
ctx.pop()
```

The error is due to this code: https://github.com/sloria/flask-marshmallow/blob/f08feafc397a09d01acbe54ec0e4251b12b9940c/flask_marshmallow/fields.py#L79-86

This behavior is incorrect because it is checking the truthiness of the `self.get_value(attr, obj)`, which may return a valid (but falsy) value , e.g.  `0`.

I think the solution is to remove this check. Will work on a fix shortly.

EDIT: Expanded the code example to clarify the bug.

**Comment by ghost** [comment]
@sloria Could it be better to change the check to `attribute_value is not None`? I don't see when anyone would build a URL with None attributes.

**Comment by sloria** [comment]
@raj-kesavan  I don't think `None` needs to be special-cased; if a user improperly tries to build a URL with `None`, then they should receive a werkzeug `BuildError`, as expected.

**Comment by sloria** [comment]
fixed as of https://github.com/marshmallow-code/flask-marshmallow/commit/4d3acfb6af2848b8ee085deed729b2f37cc5d546
