### ISSUE TITLE
getting empty

### ISSUE THREAD

**Issue by venkataramireddy123** [marshmallow-code/flask-marshmallow#107]
notifications = PRO_USERNOTIFICATIONSSchema(many=True,strict=True)
 _notifications = notifications.dump(self.PRO_USERNOTIFICATIONSs).data

showing empty data like [{}].

could any one try to find out what i missed

**Comment by sloria** [comment]
This is more likely to be a marshmallow question than a flask-marshmallow question. Can you open an issue on marshmallow's issue tracker and add more details (e.g. the code for your Schema, etc.)?
