### ISSUE TITLE
Nasted Schema with multiple fields

### ISSUE THREAD

**Issue by kakul232** [marshmallow-code/flask-marshmallow#138]
I am trying to build a role base relation between 3 model , 

UserModel : 

    class UserModel(db.Model):
        __tablename__ = 'users'
    
        id = Column(Integer, primary_key=True)
        username = Column(String(120), unique=True, nullable=False)
        password = Column(String(120), nullable=False)
        reset_token = Column(String(120), nullable=True)
        status = Column(Integer, nullable=True)
        roleofuser = db.relationship('RoleUser', backref=db.backref('roleofuser'))

after that I have created a role and user mapped model
UserRole model

    class RoleUser(db.Model):
        __tablename__ = 'role_users'
    
        id = Column(Integer(), primary_key=True)
        role_id = Column(Integer(), db.ForeignKey('role.id'))
        user_id = Column(Integer(), db.ForeignKey('users.id'))
        role_rel = db.relationship('Role',
                                   backref=db.backref('role_rel'))
        user_rel = db.relationship('UserModel',
                                   backref=db.backref('user_rel'))

And finally the Role model 
 

    class Role(db.Model):
        __tablename__ = 'role'
    
        id = Column(Integer(), primary_key=True)
        name = Column(String(50), unique=True)

After That I ma using Marshmallow schema to display the data 

    class UserScheme(ma.MOdelSchema):
        roleofuser = fields.Nested("RoleUserSchema")
        username = fields.String(required=True)
    
        class Meta:
            model = UserModel
            #fields = ("username","userrole")
    
    """ Role USER mapped """ 
    class RoleUserSchema(ma.Schema):
        user_rel = fields.Nested("UserScheme")
        role_rel = fields.Nested("RoleSchema")
        class Meta:
            model = RoleUser
    
    """Role """
    
    class RoleSchema(ma.Schema):
        roleuser_rel = fields.Nested("RoleUserSchema")
        class Meta:
            Role

Now the problem is after calling `user.query.all() ` , 
relation data is not appending on result ,
getting result like : 

    {
    roleofuser:{},
    username: abcd123
    } 

and i am expecting

```
    {
        roleofuser : {
         role_rel: {
                     id:1,
                     name: 'admin'
              }
        },
    username : 'admin232'
    }
```

**Comment by highoncarbs** [comment]
Hi, any updates on how you fixed the problem. Having the same issue

**Comment by kakul232** [comment]
yes ,  I have done mistake on my code

`roleofuser:{} ` because i have not mention relation on model 
 
**FIXES :  IN model you need to mentin relationship like this** 

`roleofuser = product = relationship('RoleUserModel')`

**Then in Schema file :** 

`roleofuser = fields.Nested("RoleUserSchema")`
