### ISSUE TITLE
Incompatibility with marshmallow version 3.0.0

### ISSUE THREAD

**Issue by rohanjaswal2507** [marshmallow-code/flask-marshmallow#147]
A new version(3.0.0) of marshmallow has been released on Aug 18, 2019. There have been some changes which break existing implementations. For example, "combat" module has been removed from marshmallow 3.0.0.

Existing applications break because flask-marshmallow requires marshmallow >= 2.0.0 which automatically downloads the latest version(incompatible) during deployments.

**Comment by sloria** [comment]
Which version of flask-marshmallow are you using? flask-marshmallow 0.10.1 should is compatible with marshmallow 3.0.0.

**Comment by rohanjaswal2507** [comment]
Thanks for the information. I was using 0.9.0

**Comment by Altiire** [comment]
```
        schema = CompanySchema(partial=True)
        company = Company.query.get_or_404(company_id)
>       company, errors = schema.load(request.json, instance=company)
E       TypeError: cannot unpack non-iterable Company object
```

schema being a ModelSchema, are you sure that current version is fully compatible ?

**Comment by sloria** [comment]
@Altiire See https://marshmallow.readthedocs.io/en/latest/upgrading.html#schemas-are-always-strict ; `load` does not return a tuple any more.

**Comment by Altiire** [comment]
Thank you, I wasn't looking at the right place !
