### ISSUE TITLE
Is there a plan that adding DEFAULT_DATETIME_FORMAT for Flask config

### ISSUE THREAD

**Issue by gotounix** [marshmallow-code/flask-marshmallow#148]
I think it's better to add a ``DEFAULT_DATETIME_FORMAT`` for global ma.DateTime.
Then we shouldn't add ma.DateTime(format=MyFormat) for each schema created by models.

**Comment by sloria** [comment]
You can use a base schema class to set a datetime format for all your schemas

```python
class BaseSchema(ma.Schema):
    class Meta:
        datetimeformat = 'rfc'
```

**Comment by gotounix** [comment]
@sloria Thanks.
