### ISSUE TITLE
Integration between flask-marshmallow and flask_sqlalchemy

### ISSUE THREAD

**Issue by joaomiranda94** [marshmallow-code/flask-marshmallow#159]
Hello there,

I'm have been trying to use the ModelSchema in my application with no success. Every time I try to pass a request from my client application to the flask app, I get the following error:

`for prop in model.__mapper__.iterate_properties:
AttributeError: module 'app.models.User' has no attribute '__mapper__'`

So, I have been following the documentation steps to initialize sqlalchemy and marshmallow correctly and I am using the db.Model to declare my models.

My doubt is, should __mapper__ be declared manually or i'm missing something:

Here are my User.py, __init__.py and my schema:

```
class User(db.Model):

    id = db.Column('id', UUID(as_uuid=True), primary_key=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow())
    last_update = db.Column(db.DateTime, onupdate=datetime.utcnow())
    name = db.Column(db.String(250), nullable=False)
    email = db.Column(db.String(250), nullable=False)
```

```
def create_app(test_config=None):
    f_app = Flask(__name__, instance_relative_config=True)

    f_app.config.from_object(config.BaseConfig)

    f_app.url_map.strict_slashes = False

    app.infrastructure.db.init_app(f_app)
    app.infrastructure.marshmallow.init_app(f_app)

    app.infrastructure.migrate.init_app(f_app, app.infrastructure.db, directory=os.path.join(f_app.root_path, 'migrations'))
    api = Api(f_app)

    from app.infrastructure.routes import register_routes
    register_routes(api)

    try:
        os.makedirs(f_app.instance_path)
    except OSError:
        pass

    @f_app.route('/', defaults={'path': ''})
    @f_app.route('/<path:path>')
    def index(path):
        return f_app.send_static_file('index.html')

    @f_app.route('/favicon.ico')
    def favicon():
        return send_from_directory(os.path.join(f_app.root_path, 'static'),
                                   'favicon.ico', mimetype='image/vnd.microsoft.icon')

    return f_app
```

the sqlalchemy and marshmallow classes are instanced and called from another package.

```
class UserSchema(marshmallow.ModelSchema):
    class Meta:
        model = User
```

**Comment by kakul232** [comment]
You need to define  __init __ on model

    ```
class User(db.Model):
 # Define Coloum

     def __init__(self, *args, **kwargs):
             super().__init__(*args, **kwargs)

```
I

**Comment by joaomiranda94** [comment]
@kakul232 I tried to do this but got the same error, here is my stacktrace

![Screenshot_2](https://user-images.githubusercontent.com/2637270/73101967-c106bb00-3ee8-11ea-871d-08e670259dd3.png)

**Comment by kakul232** [comment]
Have a look at 
#71

**Comment by joaomiranda94** [comment]
#71  is related to integration with django. Are you saying that the only way for me to integrate would be to manually declare my schemas?

**Comment by kakul232** [comment]
Hi @joaolongo , declared def __init__() method on model and try it

**Comment by joaomiranda94** [comment]
@kakul232 I plpayed a little bit aroung with the import order of my models and schemas and found the solution. The point is that my schema was being initialized before my model. Once I forced it to be initialized last it solved my issue.


Final solution was this:
```
from sqlalchemy.dialects.postgresql import UUID
from datetime import datetime

from app.infrastructure import db, marshmallow


class User(db.Model):
    __tablename__ = "user"

    id = db.Column('id', UUID(as_uuid=True), primary_key=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow())
    last_update = db.Column(db.DateTime, onupdate=datetime.utcnow())
    name = db.Column(db.String(250), nullable=False)
    email = db.Column(db.String(250), nullable=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class UserSchema(marshmallow.ModelSchema):
    class Meta:
        model = User

```
