### ISSUE TITLE
Got Vulnerability while feeding request.get_json() data to marshmallow directly .

### ISSUE THREAD

**Issue by vvksahoo** [marshmallow-code/flask-marshmallow#163]
I am using flask-marshmallow for user input validation . 
```
from marshmallow import Schema, fields, validate


class UserSchema(Schema):
    username = fields.String(required=True,
                            validate=[validate.Length(min=1, error="Field should not be empty.")])
    pincode = fields.Integer(required=True, validate=validate.Range(
        min=0, error="pincode is invalid, it should be a positive integer."))
```
In application  controller part :
```
class UserDetails(Resource):
    user_schema_obj = UserSchema()
    def post(self):
        if not request.is_json:
            return make_response(jsonify(error_dict(
                current_request_id(), "Unsupported media type, Requests must be JSON",
                415)), status.HTTP_415_UNSUPPORTED_MEDIA_TYPE)

        if not request.json:
            return make_response(jsonify(error_dict(
                current_request_id(), "Required parameter not found",
                400)), status.HTTP_400_BAD_REQUEST)
        request_jsn = UserDetails.user_schema_obj.load(request.get_json())
        username = request_jsn['username']
        pincode = request_jsn['pincode']
```
This is the way i am feeding user input to marshmallow schema . when i am doing app scan it saying ```gets user input from element **get_json**. This element’s value flows through the code without being properly sanitized or validated and is eventually stored in the server-side Session object, in post ```.
This constitutes a Trust Boundary Violation. 
Dont know how to resolve this ? Please help!

**Comment by sloria** [comment]
I'm not sure I understand the issue. What scan are you using? Is it possible that this is a false positive?

**Comment by vvksahoo** [comment]
I am using checkmarx to scan our application . ```request_jsn = UserDetails.user_schema_obj.load(request.get_json())``` , in this line i am feeding user input to marshmallow schema, basically its not understanding ,this schema will validate user input . Thats why its saying do some validation before using request.get_json().

**Comment by sloria** [comment]
I see, so it's a false positive in the scan. I'm afraid there's not much we can do in marshmallow about this. I would file an issue with checkmarx about it.

**Comment by vvksahoo** [comment]
Thanks for your response sloria. Let me know once here if you got any reply from them .

**Comment by sloria** [comment]
@vvksahoo  Sorry, I was unclear. I was suggesting that you file an issue with checkmarx. I don't have much of a stake in this since I am not a checkmarx user.
