### ISSUE TITLE
'Marshmallow' object has no attribute 'ModelSchema' when using version 12

### ISSUE THREAD

**Issue by notdesmond** [marshmallow-code/flask-marshmallow#188]
I'm not sure if this is a bug but when I'm using mashmallow 3.6.0 and marshmallow-sqlalchemy 0.23.1 with flask-marshmallow 12 I get this error 'Marshmallow' object has no attribute 'ModelSchema'.

This doesn't happen with I use flask-marshmallow 11.

The code:

class Companies(mm.ModelSchema):
    class Meta:
        model = CompaniesModel
        unknown = EXCLUDE

**Comment by sloria** [comment]
> Breaking change: ma.ModelSchema and ma.TableSchema are removed, since these are deprecated upstream.

See https://flask-marshmallow.readthedocs.io/en/latest/changelog.html#changelog .
