### ISSUE TITLE
AttributeError when initializing Marshmallow

### ISSUE THREAD

**Issue by PatrickRic** [marshmallow-code/flask-marshmallow#189]
I use Flask, SqlAlchemy and Marshmallow to build a REST API with Python.

I used pipenv to install flask, flask-sqlalchemy, flask-marshmallow and marshmallow-sqlalchemy.

Here are my dependency versions:

click==7.1.2
Flask==1.1.2
flask-marshmallow==0.12.0
Flask-SQLAlchemy==2.4.3
itsdangerous==1.1.0
Jinja2==2.11.2
MarkupSafe==1.1.1
marshmallow==2.21.0
marshmallow-sqlalchemy==0.19.0
six==1.15.0
SQLAlchemy==1.3.17
Werkzeug==1.0.1

However, when I try to initialize an instance of Marshmallow with my Flask app as a parameter, I get following Error:

  File "/Users/pro/PycharmProjects/EventPlannerAPI/app.py", line 15, in <module>
    ma = Marshmallow(app)
  File "/Users/pro/.local/share/virtualenvs/EventPlannerAPI-OoqXq5gv/lib/python3.7/site-packages/flask_marshmallow/__init__.py", line 104, in __init__
    self.init_app(app)
  File "/Users/pro/.local/share/virtualenvs/EventPlannerAPI-OoqXq5gv/lib/python3.7/site-packages/flask_marshmallow/__init__.py", line 116, in init_app
    self.SQLAlchemySchema.OPTIONS_CLASS.session = db.session
AttributeError: 'NoneType' object has no attribute 'OPTIONS_CLASS'

On StackOverflow I was told that probably a dependency is broken. Here is my whole code:

`from flask import Flask, request, jsonify
from flask_sqlalchemy import SQLAlchemy
from flask_marshmallow import Marshmallow
import os

# Init app
app = Flask(__name__)
basedir = os.path.abspath(os.path.dirname(__file__))
# Database
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir, 'db.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
# Init db
db = SQLAlchemy(app)
# Init ma
ma = Marshmallow(app)

# Run Server
if __name__ == '__main__':
    app.run(debug=True)`

**Comment by barakyo** [comment]
I'm getting this same error with the following dependency versions:
```
Flask-SQLAlchemy==2.3.2
marshmallow-sqlalchemy==0.14.0
SQLAlchemy==1.2.10
Flask==1.0.2
flask-marshmallow==0.11.0
```

**Comment by sloria** [comment]
Thanks for the report. This bug shows up if you have marshmallow-sqlalchemy<0.22.0. I have a fix PR up (https://github.com/marshmallow-code/flask-marshmallow/pull/190), and I'll release it shortly in 0.13.0
