### ISSUE TITLE
Add documentation on how to define fields in a schema manually without using an ORM

### ISSUE THREAD

**Issue by svdHero** [marshmallow-code/flask-marshmallow#207]
Currently the documentation only contains sample code and explanations about how to define fields in a schema using some ORM's `Column` function. However, I am not using any ORM and just want to define my schema explicitely like in vanilla Marshmallow, e.g.,:

```python
from marshmallow import Schema, fields, post_load, ValidationError, validates, validate

class User:
    def __init__(self, name, age, email):
        self.name = name 
        self.age = age
        self.email = email

    def __repr__(self):
        return f'{ self.name } is { self.age } years old.'

class UserSchema(Schema):
    name = fields.String(validate=validate.Length(max=100))
    age = fields.Integer()
    email = fields.Email()
    location = fields.String(required=False)

    @validates('age')
    def validate_age(self, age):
        if age > 200:
            raise ValidationError('The age is too old!')

    @post_load
    def create_user(self, data, **kwargs):
        return User(**data)

# Init Schema
user_schema = UserSchema()
users_schema = UserSchema(many=True)
```

The official documentation states

> class flask_marshmallow.Marshmallow(app=None)
> Wrapper class that integrates Marshmallow with a Flask application.
> 
> To use it, instantiate with an application:
> from flask import Flask
> app = Flask(__name__)
> ma = Marshmallow(app)
>
> The object provides access to the Schema class, all fields in marshmallow.fields, as well as the Flask-specific fields in flask_marshmallow.fields.

How exactly does `ma` provide access to `marshmallow.fields` and how do I get access to the decorators `validates` and `post_load` as well as the validator `validate.Length`?

I tried the following:
```python
from flask_marshmallow import Marshmallow 

# Init ma
ma = Marshmallow(app)

class UserSchema(ma.Schema):
    name = ma.String(validate=ma.validate.Length(max=100))
    age = ma.Integer()
    email = ma.Email()
    location = ma.String(required=False)

    @validates('age')
    def validate_age(self, age):
        if age > 200:
            raise ValidationError('The age is too old!')

    @post_load
    def create_user(self, data, **kwargs):
        return User(**data)
```
but got many `undefined variable` error messages.

**Comment by sloria** [comment]
The `Field` and `Schema` classes get attached to the `Marshmallow` instance for convenience: https://github.com/marshmallow-code/flask-marshmallow/blob/299dd87f320b1806a94c615cdedd8444ceb0fafb/src/flask_marshmallow/__init__.py#L39-L47.

The decorators aren't attached, so you'll need to import those from marshmallow.

```python
from marshmallow import validates
```
