### ISSUE TITLE
FR: Flask config field

### ISSUE THREAD

**Issue by mjpieters** [marshmallow-code/flask-marshmallow#212]
I currently am passing a lot of `current_app.config[...]` settings into schemas.

Would there be use for a `FlaskConfig` class? You'd give it a field class to use in serialisation (defaults to `fields.String`), the configuration variable name (defaults to the field name, uppercased), and use this to serialise the current value from `current_app.config`.

This would go very nicely with the current `URLFor` / `AbsoluteURLFor` fields. Example based on an active project:

```python
class ItemPresets(Schema):
    monty = ma.FlaskConfig(ma.Integer, "ACME_MONTY_PRESET")
    viking = ma.FlaskConfig(ma.Integer, "ACME_VIKING_PRESET")

class AcmeConfig(Schema):
    data_endpoint = ma.AbsoluteURLFor("rest.ham_collection")
    some_api_access_token = ma.FlaskConfig()  # serializes SOME_API_ACCESS_TOKEN as a string field.
    acme_presets = ma.Nested(ItemPresets, default=dict)
```

The field type defaults to String and config name to the uppercased field name.

Note that the field should probably default to `dump_only=True`, you wouldn't want to use this for incoming data, setting your configuration on deserialization, unless explicitly set do to so.

**Comment by sloria** [comment]
See comment in #222 

> Thanks for the PR. I think I'm going to have to pass on this since the use case here is too specific and makes too many assumptions to justify the added API surface.

If you need marshmallow validation  for your configuration and you're using environment variables per the [12 factor](https://12factor.net/config) methodology, I recommend taking a look at [environs](https://github.com/sloria/environs#usage-with-flask).

**Comment by mjpieters** [comment]
I think you misunderstood the use case here.

This is used to expose configuration stored in the standard Flask config to other consumers such as an SPA.

In the specific case were I created this field implementation, the front-end is rather TypeScript heavy but is configured using JSON embedded in a `<script>` tag, and we used Marshmallow schemas to define their structure.

The support to _set_ Flask configuration with a `FlaskConfig` field was only implemented to keep the field symmetrical, is disabled by default and was kept primitive on purpose (hence the warnings in the documentation).

On a meta level: I would have appreciated discussion on this _much, much earlier_ before I had put in the time to create a PR for this. I posted the FR 2 months ago. It would have saved us both some time.

**Comment by sloria** [comment]
I understand the use case. I still think it's too specific to justify the added code and API surface. The use case can be met without too much trouble using existing API:

```python
from flask import Flask
from flask_marshmallow import Marshmallow

app = Flask(__name__)
app.config["SOME_ACCESS_TOKEN"] = "public-token"
ma = Marshmallow(app)


class MyConfig(ma.Schema):
    my_field = ma.Str()
    some_access_token = ma.Constant(app.config["SOME_ACCESS_TOKEN"], dump_only=True)


print(MyConfig().dump(dict(my_field="foo")))
# {'some_access_token': 'public-token', 'my_field': 'foo'}
```

You could easily write a helper to improve the ergonomics a bit:

```python
def app_config_field(config_key, **kwargs):
    kwargs.setdefault("dump_only", True)
    return ma.Constant(app.config[config_key], **kwargs)


class MyConfig(ma.Schema):
    my_field = ma.Str()
    some_access_token = app_config_field("SOME_ACCESS_TOKEN")
```

>  I would have appreciated discussion on this much, much earlier before I had put in the time to create a PR for this. I posted the FR 2 months ago. It would have saved us both some time.

That would have been ideal, yes. Unfortunately, I've not been able to spend a lot of time on this lib the past couple months due to personal and professional priorities.

**Comment by mjpieters** [comment]
> ```python
> class MyConfig(ma.Schema):
>     my_field = ma.Str()
>     some_access_token = ma.Constant(app.config["SOME_ACCESS_TOKEN"], dump_only=True)
> ```

Unfortunately, that doesn't work with an [app factory](https://flask.palletsprojects.com/en/1.1.x/patterns/appfactories/), as there is no app object available at import time. This is the norm for most real-world Flask apps, you'd have to generate the schema from the app factory, directly or via a `Blueprint.record()` hook, if you have a Blueprint to associate the schema with).

It also precludes the possibility of sharing the schema between apps (as a supporting library). I'm currently building a set of related APIs, where there is overlap in models and schemas that we'll put into a shared library, and `FlaskConfig()` covers that case much better.

**Comment by sloria** [comment]
To support app factories and blueprints, you could use a `Function` field.

```python
def app_config_field(config_key, **kwargs):
    kwargs.setdefault("dump_only", True)
    return ma.Function(lambda _: current_app.config[config_key], **kwargs)

class MyConfig(ma.Schema):
    my_field = ma.Str()
    some_access_token = app_config_field("SOME_ACCESS_TOKEN")
```

But if your `FlaskConfig` field works best for your use case, then go ahead and use it. At work, we have a shared utility library with marshmallow `Field` and `Schema` classes that are shared across our services; this is a common practice.
