### ISSUE TITLE
How to return MarshalResult when use SQLAlchemyAutoSchema

### ISSUE THREAD

**Issue by yuruotong1** [marshmallow-code/flask-marshmallow#232]
when i use schema.dump , i get Python object instead of MarshalResult.

But the old  version, when using find ModelSchema, return MarshalResult.

How to return MarshalResult when use SQLAlchemyAutoSchema？

**Comment by ArthurArslanaliev** [comment]
Looks like this was changed in the marshmallow library https://marshmallow.readthedocs.io/en/stable/changelog.html#b7-2018-02-03

> Schema().load and Schema().dump return data instead of a (data, errors) tuple
