### ISSUE TITLE
ModuleNotFoundError: No module named 'flask_marshmallow'

### ISSUE THREAD

**Issue by elijahondiek** [marshmallow-code/flask-marshmallow#239]

**Comment by rimu** [comment]
I struggled with this for quite a while. In the end, all I needed to do was 

```source venv/bin/activate ```

i.e. reload by venv

**Comment by sirosen** [comment]
I'm trying to catch up on old issues in this repo and this one doesn't appear to be a valid/well-formed issue. I'm closing.
