### ISSUE TITLE
Python3.10: Distutils depreciation warning

### ISSUE THREAD

**Issue by tgross35** [marshmallow-code/flask-marshmallow#242]
Couldn't find an issue for this yet, but in py3.10 there's a warning about distutils. Should be an easy transition.

```
  /usr/local/lib/python3.10/site-packages/flask_marshmallow/__init__.py:10: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    from distutils.version import LooseVersion
```

**Comment by sirosen** [comment]
This is resolved in the main branch. I'm trying to take some time to queue up a release. Not sure exactly when it will happen, but it should be soon.
