### ISSUE TITLE
Been a while; time for a release?

### ISSUE THREAD

**Issue by utkarsh2102** [marshmallow-code/flask-marshmallow#245]
Hello,

It's been a while since the last release. Can we tag a new release, please? TIA.

**Comment by sponsfreixes** [comment]
@sirosen are you currently the only active maintainer on this project? Is more help needed?

**Comment by sirosen** [comment]
Ah, thank you for the ping! I walked away from the project for a while (been busy / the typical excuses :sweat_smile: ) and hadn't realized that I didn't do a release back when I came in here to touch on things.

It looks like I'm missing the pypi permissions needed to push out a release.
Give me a day or two to reach out and get the creds to do it.
The current `main` should be good to ship.

**Comment by sirosen** [comment]
0.15.0 is now available!

I'm starting to triage the bugs (to some degree expected) as they come in and as I'm able. Please feel free to file issues if you see any trouble.
