### ISSUE TITLE
DeprecationWarning from Flask-SQLAlchemy for app.extensions["sqlalchemy"]

### ISSUE THREAD

**Issue by woutervanoorschot** [marshmallow-code/flask-marshmallow#247]
Flask-SQLAlchemy has rewritten the way to load the extension. No longer `app.extensions["sqlalchemy"].db` but simply `app.extensions["sqlalchemy"]` see https://github.com/pallets-eco/flask-sqlalchemy/issues/698.

This is used here: https://github.com/marshmallow-code/flask-marshmallow/blob/13f673979937bc5b366863eeff4eefadfb8433d1/src/flask_marshmallow/__init__.py#L114

This is a breaking change and would require to also pin Flask-SQLAlchemy to `>3.0` in https://github.com/marshmallow-code/flask-marshmallow/blob/13f673979937bc5b366863eeff4eefadfb8433d1/setup.py#L7

**Comment by Abdur-rahmaanJ** [comment]
@sloria Any update?
