### ISSUE TITLE
Incompatible with marshmallow-sqlalchemy 0.4.0

### ISSUE THREAD

**Issue by svenstaro** [marshmallow-code/flask-marshmallow#25]
Due to [this change](https://github.com/marshmallow-code/marshmallow-sqlalchemy/commit/0f69d7da47587b6398bfc087e213706dff8657e3), flask-marshmallow is now needs some fixing to be compatible again.

**Comment by svenstaro** [comment]
Looking at this for a bit, it would appear to be enough to replace SchemaOpts with ModelSchemaOpts. I would make a pull request but I'm not entirely certain how all the new classes fit into flask-marshmallow.

**Comment by sloria** [comment]
I've cut a release (0.6.1) which fixes compatibility with marshmallow-sqlalchemy>=0.4.0. Thanks for reporting @svenstaro
