### ISSUE TITLE
Add request parsing; webargs; integrate flask-smore?

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/flask-marshmallow#26]
Brainstorming ideas for the next iteration(s) of this package:
- [ ] Add request parsing by integrating with `webargs`, which now uses marshmallow. This might be as simple as providing the [use_schema](https://github.com/sloria/webargs/blob/dev/examples/schema_example.py) decorator, which allows using a `Schema` for both input and output and a `marshal_with` decorator (just output).
- [ ] Merge [flask-apispec](https://github.com/jmcarp/flask-apispec)? Would integrate with the above request parsing module and provide automatic swagger spec generation

**Comment by sloria** [comment]
@jmcarp :v:

**Comment by taion** [comment]
Swagger integration would be amazing. I'm not 100% convinced on using e.g. `@marshal_with` decorators for serialization, though - is there a great pattern for e.g. handling "meta" data for pagination when doing this?

**Comment by jeffwidman** [comment]
:+1:  for adding optional integration of `webargs` for request parsing. I'm just starting to look into how to do this manually right now.

**Comment by rth** [comment]
I was wondering if there is any update on this? marshmallow, webargs and apispec are great, but I was not able to find any package (or even examples) for flask that look production ready using those (except for  flask-apispec which does not seem to be maintained anymore) .

**Comment by sloria** [comment]
@rth We haven't formalized what this integration will look like, but I am still open to the idea. For now, I recommend sticking with Flask-APIspec--as that project matures through production usage (yes, it is still maintained) and we become more confident in its API, we will likely revisit integrating into flask-marshmallow.

**Comment by sloria** [comment]
closing; i'm happy to have request parsing functionality live in wrapper frameworks, as they already do in [flask-smorest](https://github.com/marshmallow-code/flask-smorest) and [apiflask](https://github.com/apiflask/apiflask)
