### ISSUE TITLE
Flask deprecation warning

### ISSUE THREAD

**Issue by shonteag** [marshmallow-code/flask-marshmallow#260]
Hey folks!

First, thanks for creating this package, it's be an absolute joy to use. I have run into a small issue with a deprecation warning from Flask. You may already be aware, but it looks like [this line](https://github.com/marshmallow-code/flask-marshmallow/blob/dev/src/flask_marshmallow/__init__.py#LL114) is responsible, and will break in Flask 3.1. Here is the full warning message:

```
DeprecationWarning: The 'db' attribute is deprecated and will be removed in Flask-SQLAlchemy 3.1. The extension is registered directly as 'app.extensions["sqlalchemy"]'.
    db = app.extensions["sqlalchemy"].db
```

I'm seeing this while running Flask version 2.2.2 and flask-marshmallow version 0.14.0.

Just a friendly heads up!

**Comment by rti-ramsay** [comment]
I believe this has been fixed in this [PR](https://github.com/marshmallow-code/flask-marshmallow/pull/249/files) but this change hasn't been released yet.

**Comment by sloria** [comment]
this has been fixed
