### ISSUE TITLE
New release from dev

### ISSUE THREAD

**Issue by jgriffon** [marshmallow-code/flask-marshmallow#277]
Hello,

Thank you for this great extension. I love it
I use it with SQLAlchemy, and I can't update anymore flask-sqlalchemy because of the new extension's structure.

Would it be possible to create a new release from dev branch because problems are solved but not released as seen in this issues, PR :
 
#247 
#249 
#260

**Comment by sirosen** [comment]
Two of those were included in the v0.15.0 release earlier this year. The one which is still open is something I need to circle back around to at some point to investigate and see if it was resolved, but I haven't made time for it.

Are you using v0.15.0 and not seeing these changes included?

**Comment by jgriffon** [comment]
Thank you, you were true, my version was still 0.14.x
