### ISSUE TITLE
schema.jsonify list of sqlalchemy instances incompatible with flask.jsonify

### ISSUE THREAD

**Issue by jo-tham** [marshmallow-code/flask-marshmallow#28]
@ElvisTheKing @sloria 

continuing where #19 left off... 

I am trying to use flask-marshmallow schema.jsonify on the result of a sqlalchemy query

Using model instance is ok

```
from models.equipment import Equipment
equipments = Equipment.query.all()
equipments_schema.jsonify(equipments[0]).response

#('{\n  "date_added": "2015-10-23T11:07:46.384414+00:00", \n  "id": 1, \n  "name": "beacon"\n}', '\n')
```

List of model instances breaks

```
equipments_schema.jsonify(equipments)

#*** AttributeError: "id" is not a valid field for [<app.models.equipment.Equipment object at 0x7f5b3c11c240>, <app.models.equipment.Equipment object at 0x7f5b3c11cba8>].
```

versions

```
Flask==0.10.1
flask-marshmallow==0.6.2
-e git+https://github.com/flask-restful/flask-restful.git@54c51fd88759e2f398d566040200d2c9d51b8e5f#egg=Flask_RESTful-master
Flask-SQLAlchemy==2.0
marshmallow==2.1.3
marshmallow-sqlalchemy==0.6.0
```

I think it's because the sqlalchemy query returns a list of model instances, which is not compatible with flask.jsonify. There's some discussion in flask about this, but it sounds like that'll never be supported.

Am I missing something here? from the examples in the readme one might assume this should work. 

Otherwise, any thoughts for how to improve this?

**Comment by jo-tham** [comment]
it also seems that we have to explicitly pass many=True to schema.jsonify even when the schema instance was created with many=True

``` python
equipments_schema.jsonify(equipments, many=True)
# *** ValueError: dictionary update sequence element #0 has length 3; 2 is required
```

**Comment by jo-tham** [comment]
If the result of schema.dump is put into dictionary things work as expected;  marhsmallow `@post_dump` is convenient for this. Things work as expected (thanks @sloria marshamllow 2.0 release notes on blog).

Is this the recommended way to handle this? If so, update flask-marshmallow docs? May also affect marshmallow-sqlalchemy...

```
@staticmethod
def get_envelope_key(many):
    """Helper to get the envelope key."""
    return 'equipments' if many else 'equipment'

@post_dump(pass_many=True)
def wrap_with_envelope(self, data, many):
    key = self.get_envelope_key(many)
    return {key: data}
```

**Comment by sloria** [comment]
Yes, using a `post_dump` method to envelope the data is a fine solution. 

All `Schema.jsonify` does is dump the data and pass it to `flask.jsonify`, so jsonify's "no-collection-type" contraint still applies.

**Comment by jo-tham** [comment]
I think enhancing the docs/examples would make a better experience for new users of flask-marshmallow. 

from the readme, `all_users.data` likely can not be jsonified as indicated. Perhaps I'm missing something...

``` python
class UserSchema(ma.Schema):
    class Meta:
        # Fields to expose
        fields = ('email', 'date_created', '_links')
    # Smart hyperlinking
    _links = ma.Hyperlinks({
        'self': ma.URLFor('author_detail', id='<id>'),
        'collection': ma.URLFor('authors')
    })

user_schema = UserSchema()
users_schema = UserSchema(many=True)
```

``` python
@app.route('/api/users/')
def users():
    all_users = User.all()
    result = users_schema.dump(all_users)
    return jsonify(result.data)
    # OR
    # return user_schema.jsonify(all_users)
```

It's nice that the example is orm agnostic, but since flask-marshmallow optionally integrates with sqlalchemy it might be good to have a sqlalchemy-specific example.

**Comment by sloria** [comment]
Fair points. It might make sense to include the `@post_dump` method that adds the envelope in the example.

I would certainly appreciate a PR! =)

**Comment by jo-tham** [comment]
I can oblige on the near future

**Comment by sloria** [comment]
Thanks!

**Comment by jo-tham** [comment]
I think I'll close this.

Wrapping with {} is not desireable as collections in json should be serialized as as an array '[]'

I'm using flask restful, which automatically dumps dictionaries returned using standard json.dump. jsonify returns a flask.response object, which flask-restful skips. I think flask may go this way (support jsonifying arrays) with flask.jsonify in the near future, anyway.

**Comment by jeffwidman** [comment]
More background for anyone who hits this via Google (since I spent the last half hour researching this):

This is ultimately a Flask issue due to a security vulnerability with old browsers, not a marshmallow issue. 

They're planning to change it since modern browsers aren't vulnerable:
https://github.com/mitsuhiko/flask/issues/248

For a workaround, see: http://stackoverflow.com/questions/12435297/how-do-i-jsonify-a-list-in-flask

**Comment by jeffwidman** [comment]
FYI--I fixed this upstream: https://github.com/mitsuhiko/flask/pull/1671

Flask's `jsonify()` method now serializes top-level arrays. Details here: http://flask.pocoo.org/docs/dev/api/#flask.json.jsonify

**Comment by gpankaj** [comment]
I hit the same issue and followed this to fix it: http://stackoverflow.com/questions/30614046/displaying-database-results-in-python-flask-valueerror-dictionary-update-seque
