### ISSUE TITLE
Add fields from APIFlask?

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/flask-marshmallow#280]
apiflask has `File` and `Config` fields, which may be appropriate to have in flask-marshmallow: https://github.com/apiflask/apiflask/blob/main/src/apiflask/fields.py

as well as validators to use with `File` fields: https://github.com/apiflask/apiflask/blob/main/src/apiflask/validators.py

**Comment by sloria** [comment]
cc @greyli , you may be interested in this :)

**Comment by greyli** [comment]
Sure, I could help migrate them here. I thought about it, but it was lost on my to-do list.

I will submit a pull request to add the `Config` field.

@uncle-lv Could you help migrate the `File` related field and validators to flask-marshmallow?

**Comment by uncle-lv** [comment]
> Sure, I could help migrate them here. I thought about it, but it was lost on my to-do list.
> 
> I will submit a pull request to add the `Config` field.
> 
> @uncle-lv Could you help migrate the `File` related field and validators to flask-marshmallow?

Of course.

**Comment by sirosen** [comment]
I haven't done very much here since I first got involved on this project, but I'd be happy to help with these too!

Config seems pretty small and easy to grasp. I'll need to read up a bit on apiflask's current File tooling.

**Comment by greyli** [comment]
Created the pull request for the `Config` field: https://github.com/marshmallow-code/flask-marshmallow/pull/281

**Comment by sirosen** [comment]
Wow, these got done in a flash! I think this is good to close, but please reopen if I'm wrong.

I noticed that `Config` uses `_CHECK_ATTRIBUTE`, which feels a little like an implementation detail in `marshmallow` leaking into downstream libraries. Would it be better for the field to define `serialize` instead of `_serialize`? (I haven't thought about this very hard, so apologies if that is just wrong-headed. :smile: )

**Comment by sloria** [comment]
`_CHECK_ATTRIBUTE` isn't just an implementation detail--it's meant to be set by subclasses of `Field` when the attribute isn't meant to be accessed on the object to be serialized: https://github.com/marshmallow-code/marshmallow/blob/e099e058f8d17af08369d4485622d1c14f9084ed/src/marshmallow/fields.py#L138-L141

Config is very similar to [fields.Constant](https://github.com/marshmallow-code/marshmallow/blob/e099e058f8d17af08369d4485622d1c14f9084ed/src/marshmallow/fields.py#L2057-L2079), which sets `_CHECK_ATTRIBUTE` to `False`.

**Comment by sloria** [comment]
These changes are released in 1.0.0
