### ISSUE TITLE
Is it possible to exclude fields inside nested fields?

### ISSUE THREAD

**Issue by divs1210** [marshmallow-code/flask-marshmallow#29]
How do I effectively achieve the following without creating other versions of `AnotherThing`?

``` python
class ThingShema(Schema):
    another_thing = Nested(AnotherThing. exclude=('some.completely.random.thing',))
```

**Comment by sloria** [comment]
No, this is not yet implemented in marshmallow. There is an issue here: https://github.com/marshmallow-code/marshmallow/issues/151 . Closing this in favor of discussion on that issue.
