### ISSUE TITLE
HyperlinkModelSchema missing?

### ISSUE THREAD

**Issue by russelldavies** [marshmallow-code/flask-marshmallow#30]
`HyperlinkModelSchema` is mentioned in the docs and in docstrings but doesn't seem to actually exist anywhere. Not in this project nor marshmallow-sqlalchemy. Perhaps the documentation should be updated to refer to `HyperlinkRelated` instead?

**Comment by petertrotman** [comment]
I'm also having this issue - the Marshmallow object imported from flask_marshmallow has only Schema and ModelSchema; no HyperlinkModelSchema as the docs claim.

**Comment by geiseri** [comment]
+1 on this too.  This looks like a feature that would be very cool :)

**Comment by sandervalcke** [comment]
Same here. Adding `id = ma.UrlFor('task', id='<id>')` in the schema works as a workaround, still have to see if that works for all use cases.

**Comment by diginikkari** [comment]
I was struggling with this also. Documentation seems to be quite outdated. There are no HyperlinkModelSchema anymore. Check commit #23 which introduced HyperlinkRelated class.

I learned how to use it by checking examples from test cases introduced in #23

This can be used like this:

```
from flask_marshmallow.sqla import HyperlinkRelated

...

class AuthorSchema(ma.ModelSchema):
    class Meta:
        model = Author
    books = ma.List(HyperlinkRelated('book'))

class BookSchema(ma.ModelSchema):
     class Meta:
         model = Book
     author = HyperlinkRelated('author')
```
