### ISSUE TITLE
Serialize many-to-many

### ISSUE THREAD

**Issue by speckone** [marshmallow-code/flask-marshmallow#4]
How can I serialize a many-to-many relationship? I have the following 

https://gist.github.com/speckone/6591f424588753f3ddbb

but I'm getting:

TypeError: list indices must be integers, not str

Do you have an example I could follow?

Thanks!

**Comment by sloria** [comment]
As of marshmallow 0.6.0, you can refer to nested serializers by their class name as a string. This makes it easier to implement two way nesting: http://marshmallow.readthedocs.org/en/latest/quickstart.html#two-way-nesting

Just set up two way nesting and set `many=True` for a many-to-many relationship.

**Comment by speckone** [comment]
Thanks!
