### ISSUE TITLE
AttributeError: 'Marshmallow' object has no attribute 'HyperlinkModelSchema'

### ISSUE THREAD

**Issue by tnemalili** [marshmallow-code/flask-marshmallow#47]
ma = Marshmallow(app)
class AuthorSchema(ma.HyperlinkModelSchema):
    ....
    ......
AttributeError: 'Marshmallow' object has no attribute 'HyperlinkModelSchema'

**Comment by dequis** [comment]
Duplicate of #30, already fixed with #39

tl;dr HyperlinkModelSchema doesn't exist and never did, use HyperlinkRelated.
