### ISSUE TITLE
When dumping dates it provides a weird T inside the string for my json

### ISSUE THREAD

**Issue by rlam3** [marshmallow-code/flask-marshmallow#48]
I'm having trouble with dumping my data with an date string that has a T in the middle. Please advise.

"2016-06-02T12:25:00+00:00"

**Comment by dequis** [comment]
That's a standard ISO 8601 date as returned by datetime.isoformat(). Nothing wrong there.

https://en.wikipedia.org/wiki/ISO_8601

http://stackoverflow.com/questions/10286204/the-right-json-date-format
