### ISSUE TITLE
Support file fields

### ISSUE THREAD

**Issue by svenstaro** [marshmallow-code/flask-marshmallow#5]
It would be awesome if flask-marshmallow supported file upload fields along with a file size validator to go with it. I think this is within the scope of flask-marshmallow.

**Comment by svenstaro** [comment]
Any thoughts on this? Do you think this is within the scope of flask-marshmallow?

**Comment by sloria** [comment]
I think a field that validates files is within scope, but what would the field serialize to?

**Comment by svenstaro** [comment]
It might serialize to a file URL just like the current URL field serializes to a regular flask route. The file itself could then be fetched over javascript or something on the client (though we don't care about that). Perhaps there could even be base64 encoder optionally.

**Comment by sloria** [comment]
> It might serialize to a file URL 

Perhaps, though that would require the user to pass an endpoint and probably some getter function to compute the filename.

This issue is making me think that marshmallow should support `write_only` fields that validate/deserialize but are not included in the serialized output.

**Comment by svenstaro** [comment]
Perhaps that makes sense. In our project, we use quite a few things like that. For instance, computing a slug on the fly from a name and a date. So write_only fields would definitely make sense.

I do not see a problem with the first part of your message. It could work a lot like the current URL field (the one of which I proposed the rename for).

**Comment by sloria** [comment]
>  For instance, computing a slug on the fly from a name and a date.

Sounds more of a use case for a read-only field, no? There is an open issue for that [here](https://github.com/sloria/marshmallow/issues/61).

By the way, this illustrates that the names `read_only` and `write_only` may be confusing to users, especially when marshmallow isn't meant to do any "writes" of any kind. Anyway, that's another issue.

There is no inherent problem with having the FileField serialize to a URL. I think it could default to the file's name if an endpoint isn't provided.

+1 on this. Pull requests welcome!

**Comment by DavidUnzue** [comment]
@svenstaro When using flask-restful and it's request parser, I was able to serialize into a `werkzeug.datastructures.FileStorage` object, which is very convenient to work with:

```
parser.add_argument('files[]', action='append', type=werkzeug.datastructures.FileStorage, location=['files'])
newFile = parsed_args['files[]'][0]
```

`newFile` is now a `FileStorage` object, which I can read as a stream and write into disk.

@sloria Could something like this be included into flask-marshmallow?

**Comment by sloria** [comment]
this would be solved by https://github.com/marshmallow-code/flask-marshmallow/issues/280 . closing this for now; let's have further discussion in that issue
