### ISSUE TITLE
Can you dynamically exclude fields on dump?

### ISSUE THREAD

**Issue by dland512** [marshmallow-code/flask-marshmallow#50]
I have some nested schemas:

```
class ParentSchema(Schema):
    id = fields.Int()
    uri = fields.Url('')
    children = fields.Nested('ChildSchema', many=True, exclude=('parent',))

class ChildSchema(Schema):
    id = fields.Int()
    f = fields.String()
    parent = fields.Nested('ParentSchema', exclude=('children',))
```

It all works fine except that when I'm calling `dump` on the schema, calling `parent.children` results in a ginormous database query. The object being dumped is a SqlAlechemy object, and calling its `children` property results in lazy loading of those children from the database. The code looks like this:

```
parents = Parent.all()
schema = GameSchema()
results = schema.dump(parents, many=True)
```

I this particular case, I only need the parent records. Loading the children is wasted effort. There are, however cases, when I do need the children to be loaded. For this reason, I can't just put `load_only` on the nested fields in the schema definitions.

Is there any way to tell one call to `dump` to skip certain fields?

**Comment by joshfriend** [comment]
how about this?

```python
schema = GameSchema(exclude=['children'])
```

**Comment by j08lue** [comment]
> how about this?

So the above code by @joshfriend is a proposal, not an actual feature and currently there is no shortcut for this, right? You would need to make a separate schema for dumping, like `ParentSchemaNoChildren`.

**Comment by joshfriend** [comment]
I made the suggestion several years ago. I have not used marshmallow recently so I have no idea if this is still relevant

**Comment by sloria** [comment]
`exclude` is a valid constructor parameter that should meet the OP, so the code above should work.

**Comment by EugeneZaharchenko** [comment]
> how about this?
> 
> ```python
> schema = GameSchema(exclude=['children'])
It works! Thanks for the hint

**Comment by pkeech** [comment]
> how about this?
> 
> ```python
> schema = GameSchema(exclude=['children'])
> ```

A year later, I find this page and it still works! 

Cheers!

**Comment by UzairBinShaukat** [comment]
> how about this?
> 
> ```python
> schema = GameSchema(exclude=['children'])
> ```

What if I want to exclude only `id` field not whole children field?

**Comment by roelzkie15** [comment]
Is there an **include** version of this?

```
schema = GameSchema(include=['field_1', 'field_2'])
```

**Comment by UzairBinShaukat** [comment]
> Is there an **include** version of this?
> 
> ```
> schema = GameSchema(include=['field_1', 'field_2'])
> ```

Yes @roelzkie15  you can pass "only" argument to include a list of fields.
`schema = GameSchema(only=['field_1', 'field_2'])`

**Comment by UzairBinShaukat** [comment]
> > how about this?
> > ```python
> > schema = GameSchema(exclude=['children'])
> > ```
> 
> What if I want to exclude only `id` field not whole children field?

I got an answer to this by myself which I want to share here.
We can exclude only one field of children by following

`schema = GameSchema(exclude=['children.field_name'])`

**Comment by namgivu** [comment]
I will just go for two schema classes for your two scenario ie GameSchema00 to dump with children data, and GameSchema01 dump without children data
