### ISSUE TITLE
Using strict flag for schemas does not work as expected

### ISSUE THREAD

**Issue by ctwichell** [marshmallow-code/flask-marshmallow#51]
In my schema I have various validators associated with my data elements, a handful of data elements marked as required, and everything else I just want to have type checked.  In the Meta section of the schema definition I assign strict to True to indicate that, by default, I want Marshmallow to not only perform the validation but throw exceptions when it detects issues.

In addition to the schema I have two functions that are going to load external data into the schema and then use it.  In function A I want Marshmallow to do the error checking and validation for me, so I will not set/change the value of the strict flag when I invoke the schema.  In function B, however, I want to have control of if, when, or how the validation exceptions are thrown and as such set strict to False when I invoke the schema.

When testing function B with data that would cause the schema validation to fail, I found that Marshmallow is still throwing the validation exceptions instead of simply passing everything along to me (even though I set strict to False when invoking the schema).

If I were to flip things around (i.e. set strict to False in my schema's Meta and then set strict to True when invoking the schema) everything works just like I would expect -- when using the schema variable created with strict set to True Marshmallow does in fact throw validation errors.

Has anyone else seen this issue?  Assuming that the problem I described above is in fact not desired behavior?

**Comment by sloria** [comment]
Closing, as this issue is now stale. I recommend upgrading to marshmallow 3, which gets rid of strict more altogether (strictness by default). If you're stuck on marshmallow 2 and are still experiencing on this issue, feel free to comment with a minimal repro case and we can diagnose.
