### ISSUE TITLE
Possible to disable sqlalchemy warning?

### ISSUE THREAD

**Issue by vimalloc** [marshmallow-code/flask-marshmallow#53]
I have sqlalchemy installed in my project and I'm using it for some behind the scenes sqlite3 stuff, but nothing relating to marshmallow. I do not have marshmallow-sqlalchemy installed. When I import flask-marshmallow, I get the following warning:

```
UserWarning: Flask-SQLAlchemy integration requires marshmallow-sqlalchemy to be installed.
```

Is there any way I can disable this without installing marshmallow-sqlalchemy?

**Comment by sloria** [comment]
I suppose you could use `catch_warnings` to prevent the warning from being issued:

```python
import warnings

with warnings.catch_warnings():
     from flask_marshmallow import Marshmallow
```

**Comment by lafrech** [comment]
Same use case.

I had to add a line to @sloria's code example above.

```python
import warnings

# https://github.com/marshmallow-code/flask-marshmallow/issues/53
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    from flask_marshmallow import Marshmallow
```

See https://docs.python.org/3.5/library/warnings.html#temporarily-suppressing-warnings.
