### ISSUE TITLE
How to use HyperLinkRelated when endpoint's arguments are > 1?

### ISSUE THREAD

**Issue by ev-agelos** [marshmallow-code/flask-marshmallow#54]
I am not sure if I use this correctly but my use case is that i have users(table) and subscribers(association table which maps user to another user etc..) so my endpoints are like this:
`/api/users/<int:id>/subscribers/` and
`/api/users/<int:id>/subscribers/<int:subscriber_id>`

Looking at the [code](https://github.com/marshmallow-code/flask-marshmallow/blob/pypi/flask_marshmallow/sqla.py#L64) I see that `kwargs = {self.url_key: key}` which means i can not pass more than the `url_key`(docs specify this).

What i expect is something like this when i request `/api/users/1`
```js
{
  'username': 'john',
  'email': 'email@john.com',
  'subscribers': [
    '/api/users/1/subscribers/1',
    '/api/users/1/subscribers/4',
    ...
  ]
}
```
Im not expert what so ever but i understand that either i change my endpoints to:
`/api/subscribers/` and `/api/subscribers/<int:id>` .. or?

**Comment by ev-agelos** [comment]
I think my mistake is that I am trying to use HyperlinkRelated for a ForeignKey, I guess I need to use URLFor.
I am closing the issue

Edit: I was wrong in my previous statement, still I do not know what I am supposed to do..nobody answered 1 month now so i am not re-opening it.

Edit2: It worked! My mistake was while I was testing I wasn't adding related data!

**Comment by mmasztalerczuk** [comment]
Could you tell how did you build a link with more than one argument? I'm not able to do that with HyperLinkReleated

**Comment by ev-agelos** [comment]
@mmasztalerczuk In these two files I used HyperlinkRelated:
https://github.com/ev-agelos/PyBook/blob/f410d17f3bf1be8edb146910c08cb1e928b6d925/bookmarks/models.py
https://github.com/ev-agelos/PyBook/blob/f410d17f3bf1be8edb146910c08cb1e928b6d925/bookmarks/users/models.py#L113

Almost 2 years passed from when I was writing that code(playing with flask etc) so I need to read the flask docs to remember what this HyperlinkRelated is :) I might try in the evening. The project still exists and it is served so assume the code works :)

Edit: @mmasztalerczuk  Hmm l can't find any endpoint in my code havind 2 "ids", probably i gave up on it, maybe I thought that I made it to work but I didn't, I should have updated my comment, sry I can't help you :/
