### ISSUE TITLE
Is there a specific way to format datetime in json?

### ISSUE THREAD

**Issue by rlam3** [marshmallow-code/flask-marshmallow#55]
Is there a specific way to format datetime in json?

Some of my json dates come out as "Tue, 22 Sep 2015 10:17:00 GMT" and some come out as "2015-02-03T15:40:36.078358+00:00"

**Comment by rlam3** [comment]
https://github.com/marshmallow-code/marshmallow/issues/566 
Could this be a flask-marshmallow issue?

**Comment by rlam3** [comment]
Been trying to narrow down the error. So when using flask-sqlalchemy with this package. It looks like the second to last and last pagination being dumped with flask-marshmallow does the weird GMT string. But if I isolated my data to the data entity with "Tue, 22 Sep 2015 10:17:00 GMT" and displayed it on the first pagination  it gives me back the proper string.... 
```json
"2015-09-25T10:17:00+00:00", 
```

**Comment by sloria** [comment]
The `fields.DateTime` class should format consistently serialize datetimes in the same format (iso8601 by default), so I'm unsure why you are getting different results. Can you post the `Schema` code you are using to serialize your objects?

**Comment by rlam3** [comment]
```python
class MySchema(ma.Schema):

    class Meta:
        # Fields to expose
        fields = ( 
                    'expiry_date',
        )
```

my sqlalchemy object
```python

class MyObject(Base):

    expiry_date = db.Column('expiry_date',
        db.DateTime()
    )

```

json
```json
      "expiry_date": "Fri, 25 Sep 2015 10:17:00 GMT", 
```

**Comment by sloria** [comment]
Ah, you are using [implicit field creation](https://marshmallow.readthedocs.io/en/latest/quickstart.html#refactoring-implicit-field-creation), which means that the field class for `expiry_date` will be inferred from the `expiry_date` attribute on your model. What happens if you explicitly declare the `expiry_date` field as a `DateTime`?

```python
class MySchema(ma.Schema):
    expiry_date = ma.DateTime()
```

**Comment by rlam3** [comment]
@sloria you da bauss !!! 

setting this worked!! but could you please clarify if it is possible to update my model attribute with the same format? is there a setting on the datetime.datetime to set?

**Comment by sloria** [comment]
`ma.DateTime` will deserialize to a `datetime.datetime`, so you should be able to update your model attribute with the deserialization result.

**Comment by rlam3** [comment]
so it would be myObject.expriy_date = datetime.datetime(...) like this?

**Comment by sloria** [comment]
I was thinking more along the lines of:

```python
schema = MySchema()
valid_data, errors = schema.load(request.get_json())
# ... handle errors...
my_object.expiry_date = valid_data['expiry_date']  # this is a datetime
```

**Comment by sloria** [comment]
Closing this for now. Feel free to reopen if you have further questions on this topic.
