### ISSUE TITLE
AttributeError: 'Marshmallow' object has no attribute 'ModelSchema'

### ISSUE THREAD

**Issue by mosdevly** [marshmallow-code/flask-marshmallow#56]
Using the latest 0.7.0. I installed the build on a different machine and I only get this error on this machine.

Upon inspecting the module, `marshmallow` indeed does NOT have a `ModelSchema`. Is this a bug or have I screwed something up? I haven't upgraded anything and I don't get this error on a different machine (both are running the latest Ubuntu 16 LTS)
```
Out[2]: <flask_marshmallow.Marshmallow at 0x7f96d8f2a9b0>

In [3]: vars(marshmallow)
Out[3]: 
{'AbsoluteURLFor': flask_marshmallow.fields.AbsoluteURLFor,
 'AbsoluteUrlFor': flask_marshmallow.fields.AbsoluteURLFor,
 'Bool': marshmallow.fields.Boolean,
 'Boolean': marshmallow.fields.Boolean,
 'Constant': marshmallow.fields.Constant,
 'Date': marshmallow.fields.Date,
 'DateTime': marshmallow.fields.DateTime,
 'Decimal': marshmallow.fields.Decimal,
 'Dict': marshmallow.fields.Dict,
 'Email': marshmallow.fields.Email,
 'Field': marshmallow.fields.Field,
 'Float': marshmallow.fields.Float,
 'FormattedString': marshmallow.fields.FormattedString,
 'Function': marshmallow.fields.Function,
 'Hyperlinks': flask_marshmallow.fields.Hyperlinks,
 'Int': marshmallow.fields.Integer,
 'Integer': marshmallow.fields.Integer,
 'List': marshmallow.fields.List,
 'LocalDateTime': marshmallow.fields.LocalDateTime,
 'Method': marshmallow.fields.Method,
 'Nested': marshmallow.fields.Nested,
 'Number': marshmallow.fields.Number,
 'Raw': marshmallow.fields.Raw,
 'Schema': flask_marshmallow.schema.Schema,
 'Str': marshmallow.fields.String,
 'String': marshmallow.fields.String,
 'Time': marshmallow.fields.Time,
 'TimeDelta': marshmallow.fields.TimeDelta,
 'URL': marshmallow.fields.Url,
 'URLFor': flask_marshmallow.fields.URLFor,
 'UUID': marshmallow.fields.UUID,
 'Url': marshmallow.fields.Url,
 'UrlFor': flask_marshmallow.fields.URLFor}
```
Thanks.

**Comment by mosdevly** [comment]
Nevermind. Problem with requirements file versioning ...sorry for the trouble.

**Comment by sklarsa** [comment]
@Protosac I'm running into this same problem.  What did you do to fix it?  Omitting the irrelevant parts, my `requirements.txt` looks like this:
```
flask-marshmallow==0.8.0
flask-sqlalchemy==2.3.0
marshmallow==2.13.6
sqlalchemy==1.1.14 
```

**Comment by prakash09** [comment]
@sklarsa install marshmallow-sqlalchemy package also.
`pip install marshmallow-sqlalchemy`

**Comment by tispratik** [comment]
Would the following configuration work:

```
marshmallow==2.15.0
marshmallow-sqlalchemy==0.13.2
sqlalchemy==1.0.15
```

I am getting an error when trying to retrieve the attribute value after json loads:
```AttributeError: 'UnmarshalResult' object has no attribute 'my_custom_attr'```

**Comment by Ludrique** [comment]
I ran into the same problem and when I run pip install marshmallow-sqlalchemy I get 'Requirements already satisfied'

**Comment by LukeLaScala** [comment]
@Ludrique same issue that I'm having, did you fix it?

**Comment by Ludrique** [comment]
$ Python -m pip install --upgrade pip
$pip install -U marshmallow-sqlalchemy 

#the above commands will upgrade both pip and marshmallow-sqlalchemy

**Comment by sumityadavs7y** [comment]
> Would the following configuration work:
> 
> ```
> marshmallow==2.15.0
> marshmallow-sqlalchemy==0.13.2
> sqlalchemy==1.0.15
> ```
> 
> I am getting an error when trying to retrieve the attribute value after json loads:
> `AttributeError: 'UnmarshalResult' object has no attribute 'my_custom_attr'`

instead of using `object.my_custom_attr` use `object.data.my_custom_attr`
this worked for me 
refer here https://flask-marshmallow.readthedocs.io/en/latest/

**Comment by NaturalBornCamper** [comment]
Same issue here, "marshmallow-sqlalchemy" is already installed, tried uninstalling before, same.

Problems started happening randomly after I installed "webargs". Tried removing webargs after that, still nothing. What's weird is that it's going through some other schemas without trouble. But this one schema pops an error, while being very simple and no different than otehrs

**Comment by peterschutt** [comment]
@NaturalBornCamper they dropped support for ModelSchema from this library in 0.12 (just released). Perhaps when you installed webargs, this library was upgraded too? The ModelSchema is still in marshmallow-sqlalchemy, so `from marshmallow_sqlalchemy import ModelSchema` will still work (for a while at least).

**Comment by NaturalBornCamper** [comment]
Damn, you are completely right, an upgrade was pushed just as it stopped working, never noticed! Downgraded to 0.11 to test and it works!

No idea how I will fix this however, I used a ma.py file
```
from flask_marshmallow import Marshmallow
ma = Marshmallow()
```

Then in my schema:
```
from ma import ma
class WebsiteSchema(ma.ModelSchema):
    platforms= ma.Nested(PlatformSchema, many=True)
```

So I can't just import `ModelSchema` from `marshmallow_sqlalchemy`, I'll have to look how the blip I can fix this hehe, thanks for the help!

**Comment by sloria** [comment]
See https://github.com/marshmallow-code/flask-marshmallow/blob/dev/CHANGELOG.rst#0120-2020-04-26 . It is recommended that you use the newer `SQLAlchemySchema` rather than `ModelSchema`.

**Comment by NaturalBornCamper** [comment]
Ah, that's what I was looking for (the new recommended way), but in the docs instead, thanks for pointing in the right direction!
