### ISSUE TITLE
Circular imports

### ISSUE THREAD

**Issue by aminalaee** [marshmallow-code/flask-marshmallow#57]
I have a Flask app that has a structure like the following:

```
project
  -- users
    __init__.py
    models.py
    views.py
    serializers.py
  -- genres
    __init__.py
    models.py
    views.py
    serializers.py

```
I have a ModelSchema class in one of my folders that uses models.py from the other folder. SQLAlchemy by default solves this problem by using the string name of the class but I get circular import errors in Marshmallow SQLAlchemy. Is there a way to solve this? Or shoud I change my structure?

**Comment by Msiavashi** [comment]
i have the same problem and its really bothering . does anyone know how to solve this ?

**Comment by sloria** [comment]
See https://github.com/marshmallow-code/flask-marshmallow/issues/143; the solution is to keep the schemas in a separate module from models and ensure that models are all initialized before schemas are initialized.

This needs to be documented better, as suggested on the linked issue.
