### ISSUE TITLE
SyntaxError: Python 2.6.6...

### ISSUE THREAD

**Issue by ctomatis** [marshmallow-code/flask-marshmallow#60]
File "/usr/lib/python2.6/site-packages/flask_marshmallow/fields.py", line 127
    for key, value in iteritems(d)
      ^
SyntaxError: invalid syntax

**Comment by sloria** [comment]
That line is a dictionary comprehension, which is not valid in Python 2.6. flask-marshmallow only supports Python>=2.7 and >=3.3.
