### ISSUE TITLE
from marshmallow import ( ImportError: cannot import name fields

### ISSUE THREAD

**Issue by handersonc** [marshmallow-code/flask-marshmallow#66]
I´m getting this when i try to run my project with Flask in a virtualenv

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    from flask_marshmallow import Marshmallow
  File "C:\Users\hcontreras\Documents\virtuales\MarketingProject\lib\site-packages\flask_marshmallow\__init__.py", line 14, in <module>
    from marshmallow import (
ImportError: cannot import name fields

**Comment by sloria** [comment]
Can you verify that marshmallow is installed in your virtualenv? What is the output of `pip freeze | grep -i marshmallow`?

**Comment by handersonc** [comment]
Yes, I have it installed in my virtualenv

the output of the command <pip freeze | grep -i marshmallow> is:

flask-marshmallow==0.8.0
marshmallow==2.13.5
marshmallow-sqlalchemy==0.13.1

if I remove the line from flask_marshmallow import Marshmallow the error disappear

**Comment by sloria** [comment]
I wonder if you're running into an import conflict. Do you happen to have a file called `fields.py` in your project?

**Comment by handersonc** [comment]
No Steven.

I just have a couple of fields and i don't have one called fields.py

**Comment by sloria** [comment]
And no files called "marshmallow.py"?

**Comment by handersonc** [comment]
Neither.

**Comment by sloria** [comment]
Do you get the same error if you just import `marshmallow.fields` in the same file?

```python
from marshmallow import fields
```

**Comment by handersonc** [comment]
Hi Steven sorry the delay and thanks for your time.

What I did was create a new virtualen and that worked for me.

Thanks so much again

**Comment by pranavchandran** [comment]
new version not suppor it ?
